version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=adminpass
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_email_password
      - MAIL_FROM=your_email@gmail.com
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend